# Adapted from:
# https://github.com/Exopy/exopy/blob/master/.travis.yml
# https://gist.github.com/dan-blanchard/7045057

sudo: false
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=3.5 CONDA_PY=35 QT_VERSION=5
    - env: PYTHON=3.6 CONDA_PY=36 QT_VERSION=5

before_install:
  # install Miniconda
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH
  - travis_retry conda update --yes conda
  # set up environment
  - conda create -n travisci python=$PYTHON
  - source activate travisci
  - conda config --append channels conda-forge
  - conda install -q pyqt=$QT_VERSION numpy matplotlib scikit-rf

# Install packages
install:
  - conda build conda -q
  - conda install p13pt --use-local -q

# Run test
script:
  - echo "Test test test"

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
