# Adapted from:
# https://github.com/Exopy/exopy/blob/master/.travis.yml
# https://gist.github.com/dan-blanchard/7045057

language: python

sudo: false
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=2.7 CONDA_PY=27 QT_VERSION=5
    - env: PYTHON=3.7 CONDA_PY=37 QT_VERSION=5

before_install:
  # install Miniconda
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH
  - conda config --set always_yes yes
  - travis_retry conda update conda
  - conda install conda-build anaconda-client -q  
  
  # set up environment
  - conda create -n travisci python=$PYTHON
  - source activate travisci
  #- conda config --append channels conda-forge
  #- conda install -q pyqt=$QT_VERSION numpy matplotlib lmfit scikit-rf
  - conda install -q pyqt=$QT_VERSION numpy matplotlib scikit-rf

# Install packages
install:
  - cd $TRAVIS_BUILD_DIR
  - conda build conda -q
  - conda install p13pt --use-local -q

# Run test
script:
  - echo "Test test test"

# Calculate coverage
after_success:
  - echo "Success woohoo"
