package:
  name: p13pt
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') +
             ( '' if environ.get('GIT_DESCRIBE_NUMBER', '0')  == '0' else
              ('.post' + environ.get('GIT_DESCRIBE_NUMBER', '0' )
               )
           )}}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}

requirements:
  host:
    - python
  run:
    - python
    - pyqt >=5
    - scikit-rf
    - lmfit
    - matplotlib
    - numpy
    - pyvisa
    - pywin32 # [win]

test:
  imports:
    - P13pt
    - P13pt.drivers
    - P13pt.graphulator
    - P13pt.mascril
    - P13pt.spectrumfitter

app:
  entry: p13pt
  icon: icon_48x48.png
  summary: P13pt

about:
  home: https://github.com/HolgerGraef/P13pt
  license: MIT
  license_file: LICENSE
  summary: Instrument drivers, plotting and fitting tools for high frequency electronics
